version: '3.8'

services:
  web:
    build: .
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
    networks:
      - app_network

volumes:
  bundle_data:

networks:
  app_network:
